name: MyTasks Build Workflow

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Jdk Setup
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          java-package: jdk
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Build project
        run: ./gradlew assemble
      - name: Build Debug Apk
        run: bash ./gradlew :app:assembleDebug
